### ISSUE TITLE
Component exception,Invalid hook call.hooks can be called inside of the body

### ISSUE THREAD

**Issue by attachi20** [hungvu193/react-native-rasa#1]
import React from 'react';
import {SafeAreaView, StatusBar, StyleSheet} from 'react-native';
import RNRasa from 'react-native-rasa';
// your rasa host, for example:
const HOST = 'http://localhost:5005';
const App = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView style={{
    flex: 1,
  }}>
        <RNRasa 
          host={HOST}
          onSendMessFailed={(error) => console.log(error)}
          emptyResponseMessage="Sorry, I don't understand"
          onEmptyResponse={() => console.log("Handle with your custom action")}
        />
      </SafeAreaView>
    </>
  );
};

export default App;

**Comment by hungvu193** [comment]
Hi @attachi20, can you please reproduce this in a sample project and let me know?

**Comment by attachi20** [comment]
> Hi @attachi20, can you please reproduce this in a sample project and let me know?

hi @hungvu193  i solve thisissue by using yarn add react-native-rasa thanks

**Comment by hungvu193** [comment]
@attachi20 I'm glad you solved it.
