### ISSUE TITLE
Video option not working

### ISSUE THREAD

**Issue by sohomsaha1** [hungvu193/react-native-rasa#13]
When I try and display a video through the chat interface it is just a blank grey textbox.

**Comment by hungvu193** [comment]
@jonra1993 can you help please?

**Comment by vargasjona** [comment]
Hello, @sohomsaha1 which format video are you using? is the problem on iOS or Android? What happens when you use this video http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by hungvu193** [comment]
I'll close it for now, feel free to reopen.
