### ISSUE TITLE
react-native-rasa not found after installation

### ISSUE THREAD

**Issue by kalmansour** [hungvu193/react-native-rasa#16]
After following installation steps, i get an error that react-native-rasa could not found in my project <img width="401" alt="Screen Shot 2023-05-09 at 6 15 15 PM" src="https://github.com/hungvu193/react-native-rasa/assets/63953899/14328a83-0757-4643-83ba-d0551b36beb5">
<img width="387" alt="Screen Shot 2023-05-09 at 6 15 32 PM" src="https://github.com/hungvu193/react-native-rasa/assets/63953899/2e90c0d7-16bf-4b9e-834c-e5c73b8b8863">

**Comment by hungvu193** [comment]
in your package.json, I only saw `rasa`, you should add `react-native-rasa` instead of `rasa`.

**Comment by kalmansour** [comment]
I get the following errors when i run npm i react-native-rasa
<img width="723" alt="Screen Shot 2023-05-16 at 9 56 22 AM" src="https://github.com/hungvu193/react-native-rasa/assets/63953899/2e6ac732-ddee-4c72-9a95-be88f73676cc">

**Comment by hungvu193** [comment]
@kalmansour Please install patch-package globally, this package use patch-package to apply patch from react-native-light-box.
so you need to run the follow command before install react-native-rasa:
```
npm i -g patch-package
```
