### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by himikox** [hungvu193/react-native-rasa#3]
Hello , I get an invalid hook call error when I access the screen , any idea why?
![image](https://user-images.githubusercontent.com/58792456/122657414-57c9bc80-d15b-11eb-8226-284e4c777200.png)

**Comment by hungvu193** [comment]
Can you please provide your react native version and full of your error log?

**Comment by himikox** [comment]
react native version : 3.2.0
![image](https://user-images.githubusercontent.com/58792456/122685318-746cff80-d202-11eb-9ccc-8a8644091648.png)

**Comment by hungvu193** [comment]
I though that your problem 's duplicate react, can you please try the following command:
```
cd node_modules/react-native-rasa && npm link ../react
```
After that try to run your app once again.

**Comment by himikox** [comment]
i did it and nothing changed :(

**Comment by hungvu193** [comment]
Did the command run successfully?

**Comment by himikox** [comment]
yes it did

**Comment by himikox** [comment]
actually i used yarn link instead because i already have  a problem with any npm command , might that be the reason?

**Comment by hungvu193** [comment]
you should use npm link, I think so.

**Comment by hungvu193** [comment]
https://github.com/hungvu193/react-native-rasa/issues/1

**Comment by himikox** [comment]
ok now i did "npm link ../react force" and it worked but now it shows me this error 

 ERROR  Invariant Violation: No callback found with cbID 8080 and callID 4040 for module <unknown>. Args: '["{\"stack\":[{\"file\":\"D:\\\\auth\\\\react-navigation-v5-mix\\\\node_modules\\\\@babel\\\\runtime\\\
\helpers\\\\constr...(truncated)..."]'

**Comment by himikox** [comment]
![image](https://user-images.githubusercontent.com/58792456/122754471-9fe7fc80-d28b-11eb-902a-265cf514d009.png)

**Comment by hungvu193** [comment]
that's werid, please provide your code in a public repository, I will take a look at it.

**Comment by himikox** [comment]
hey , i figured it out and it's working well . I still have a question though , how can i make add a button so the user can send an image? thanks

**Comment by hungvu193** [comment]
@himikox  Can you share with me how to resolve this? It's working well every time I run it, but I want to make sure it work well in another users side too, this library 's inherited from react-native-gifted-chat btw, so you can use all the props from it. In this case I think you need `renderActions` props from `react-native-gifted-chat`. You can take a look at this example file: 
https://github.com/FaridSafi/react-native-gifted-chat/blob/master/App.tsx
