### ISSUE TITLE
 Error: "TypeError: Network request failed"

### ISSUE THREAD

**Issue by Priiyam** [hungvu193/react-native-rasa#4]
Hi,

I'm trying to setup this library for a physical android and iOS device. I have setup all servers and my bot works on web with this [library](https://github.com/botfront/rasa-webchat), however on mobile I'm continuously getting this error on both my devices.

[TypeError: Network request failed]

So basically only one way message from my side works and i get above error in terminal. Bot and servers are setup correctly in accordance to your docs and works because as i mentioned, on web it's working using above library. I have tried all the solutions in stackoverflow from this [page](https://stackoverflow.com/questions/38418998/react-native-fetch-network-request-failed) and also double made sure `rasa run --enable-api --cors "*" ` command. This issue still persist. Any solution for this?

**Comment by hungvu193** [comment]
Hi Priiyam,
Can you try your request with postman? And can you provide the piece of code, this library use rest, it 's little bit difference with rasa-webchat which uses socket-io.

**Comment by Priiyam** [comment]
Hi @hungvu193 
Yes, below is the screenshot from postman:

![image](https://user-images.githubusercontent.com/19545672/125622016-1bd2250a-7a99-470d-b252-ef669cd83315.png)

As you can see there isn't any problem with the bot setup from what i can see. Is there anything you could think of that maybe causing the issue? Maybe narrow it down from the error i posted above. 

I didn't get you on the "can you provide the piece of code"? Which piece of code? If it's the original source code, it's something i'm not bound to share but i could create a new react native project and maybe share the source code for it incase the same issue occurs. I'm using react native 0.63.4

**Comment by hungvu193** [comment]
which host did you pass to RNRasa Component?
As I can see, you should pass it as `http://localhost:5005`

**Comment by Priiyam** [comment]
Yes @hungvu193 , I had done all of above. Again, there wasn't any problem with the bot setup. I figured it out for iOS, had to use ipv4 address instead of locahost. It worked. Thanks!
