### ISSUE TITLE
Gifted Chat properties do not work

### ISSUE THREAD

**Issue by ghost** [hungvu193/react-native-rasa#5]
Great library. However was unable to change Gifted chat props like placeholder.

`<RNRasa
         host={HOST}
         onSendMessFailed={(error) => console.log(error)}
         emptyResponseMessage="Sorry, I didn't understand"
         placeholder = "Ask me anything"
       />
`

The placeholder remains the same as the default value. 
Kindly do have a look.

**Comment by hungvu193** [comment]
Hi @Ashvin003 , thanks for your feedback, let me take look, I'm quite busy atm but I will get back to you ASAP.

**Comment by hungvu193** [comment]
@Ashvin003 Please use version 0.0.9, I resolved it in that version, feel free to reopen if you still got this issue.

**Comment by ghost** [comment]
Thanks 😀, will check it out right now.
